dbt_dskola_project:
  outputs:
    dev:
      dbname: datawarehouse_dbt
      host: localhost
      pass: '12345678'
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: data-ninja
  target: dev
